# ===================================================================
# DM JHipster Sample Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: DM JHipster Registry config server
    status: Connected to the JHipster Registry config server, using https://github.com/datamanagementitalia/jhipster !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
    logging:
        logstash:
            enabled: true
            host: 10.10.252.54
            port: 5000
            queueSize: 512
    metrics:
        logs:
            enabled: true
            reportFrequency: 60 # seconds
# DM 
dm:
    logging:
        logpath: /app/log/
        logstash:
            enabled: true
            host: 10.10.252.54
            port: 5000
            queueSize: 512
            monitoringhost: 10.10.252.54
            monitoringport: 5000
            monitoringkey: Message-ID
            monitoringqueueSize: 512
    resilienza:
        tempo_attesa: 5000 #in millisecondi
        massimo_tentativi: 2
    mail:
        cdApl: BPE
        cdRepo: FSYS
        idUser: admin
        
# DM - Rabbit Config
spring:
    rabbitmq:
        host: akronext-rabbitmq
        port: 5672
        password: guest
        username: guest
        listener:
            simple:
                acknowledge-mode: manual
                prefetch: 1
    datasource:                     #mcsmaildownload
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:oracle:thin:@//192.168.227.132:1521/ORCL.DMPA.ITA
        username: DM_CONDIV_ENTI_PAL
        password: cui2010
        auto-commit: false
        hikari:
            auto-commit: false
#mcsmaildownload            
condiventi:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:oracle:thin:@//192.168.227.132:1521/ORCL.DMPA.ITA
        username: DM_CONDIV_ENTI_PAL
        password: cui2010
        auto-commit: false
        hikari:
            auto-commit: false
procedimenti:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:oracle:thin:@//192.168.227.132:1521/ORCL.DMPA.ITA
        username: DM_PAL_PROCEDIMENTI
        password: cui2010
        driver-class-name: oracle.jdbc.OracleDriver
        auto-commit: false
        hikari:
            auto-commit: false
login:
  datasource:
    auto-commit: false
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      auto-commit: false
    password: cui2010
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//192.168.227.132:1521/ORCL.DMPA.ITA
    username: DM_LOGIN_PAL            
mailgw:
    datasource:
        driverClassName: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//192.168.227.132:1521/ORCL.DMPA.ITA
        username: akromail
        password: password  
filemanager:
    datasource:
       type: com.zaxxer.hikari.HikariDataSource
       driver: org.postgresql.Driver
       url: jdbc:postgresql://dbFilemanager:5432/db_filemanager
       username: postgres
       password: password
       hikari:
           auto-commit: false
mailagent:
  autostart: true            #se a true parte il servizio di download all'avvio dell'applicazione
  oneshot: true               #se a true il servizio di download girerà una sola volta e poi terminerà
  imap:
    - address: info@wleapi.net
      host: mail.register.it
      password: Giugno2019
      port: 143
      socketFactory_fallback: false
      socket_factory_port: 143
      ssl_enable: false
      starttls_enable: false
      user: info@wleapi.net
    - address: info@wleapi.net
      host: mail.register.it
      password: Giugno2019
      port: 143
      socketFactory_fallback: false
      socket_factory_port: 143
      ssl_enable: false
      starttls_enable: false
      user: info@wleapi.net      
    #- address: Dm.test@pec.it
    #  host: imaps.pec.aruba.it
    #  password: Giugno2019
    #  port: 993
    #  socketFactory_fallback: false
    #  socket_factory_port: 993
    #  ssl_enable: true
    #  starttls_enable: false
    #  user: Dm.test@pec.it           
  destination:
    rabbitmq:
      exchange_durable: true
      exchange_name: EXCHANGE_DOWNLOAD
      exchange_type: topic
      queue_routing_key: ROUTCODA
      server_host_name: akronext-rabbitmq
      server_password: download
      server_port: 5672
      server_user_name: download
  transport:
    action_after_process: move
    content_type: text/plain
    folder: inbox
    move_after_process: inbox.processed
    poll_interval: 1
    protocol: imap
